POST http://localhost:3000/reports
Content-Type: application/json

{
  "make": "toyota",
  "model": "corolla",
  "year": 1980,
  "mileage": 100000,
  "longitude": 0,
  "latitude": 0,
  "price": 50000
}

### Aprove an existing report
PATCH http://localhost:3000/reports/5
Content-Type: application/json

{
  "approved": false
}
